version: '0.0.{build}'
image: Visual Studio 2017

# Setup
pull_requests:
  do_not_increment_build_number: true

environment:
  SONARQUBE_TOKEN:
    secure: MTBDDF4aTiFIZFcSrOBkcmtDQnZiHx7R+Zozs8FXmpEXHt0ckiPqET8o7vj6LMBN
  NUnitConsoleVersion: 3.8.0
  OpenCoverVersion: 4.6.519
  CoverallsVersion: 1.4.2
  COVERALLS_REPO_TOKEN:
    secure: v31ShF3jpWCFELwt8iDTmUiKNB/5wZWMqy1EsCK/8LnT73kMlPjiK0ZL1rqIMjeo

# Setup build version
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $env:Build_Version = "$($env:APPVEYOR_REPO_TAG_NAME.Replace('v', ''))";
    }
    else
    {
        $env:Build_Version = "$($env:APPVEYOR_BUILD_VERSION)";
    }

# Installation
install:
# Chocolatey SonarQube
  - cinst msbuild-sonarqube-runner

# Assembly infos & csproj patching
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '$(Build_Version)'
  assembly_file_version: '$(Build_Version)'
  assembly_informational_version: '$(Build_Version)'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(Build_Version)'
  package_version: '$(Build_Version)'
  assembly_version: '$(Build_Version)'
  file_version: '$(Build_Version)'
  informational_version: '$(Build_Version)'

# Build configurations
platform:
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Build
before_build:
  - nuget restore

build:
  verbosity: normal

build_script:
  - ps: SonarScanner.MSBuild.exe begin /k:"tests_project" /d:sonar.organization="kernelith-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONARQUBE_TOKEN"
  - msbuild
  - ps: SonarScanner.MSBuild.exe end /d:"sonar.login=$env:SONARQUBE_TOKEN"

before_test:
# NuGet packages for coverage
  - ps: nuget install NUnit.Console -Version $env:NUnitConsoleVersion -OutputDirectory tools
  - ps: nuget install OpenCover -Version $env:OpenCoverVersion -OutputDirectory tools
  - ps: nuget install coveralls.io -Version $env:CoverallsVersion -OutputDirectory tools

after_test: 
# Coverage
  - ps: .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[*.Test*]*" -target:".\tools\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -output:coverage.xml
  - ps: .\tools\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r $env:COVERALLS_REPO_TOKEN

# Artifact
artifacts:  
  - path: '**\bin\Release\*.nupkg'
    name: NuGet

# Deploy
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/kernelith-ci/api/v2/package
    api_key:
      secure: ANF+joC2B+NahxCFbLPOjNvEAo36F2F4QJu6zLwoIf2I9KwkxKyCSuNxDpLmJmtU
    skip_symbols: true
    on:
      configuration: Release
  - provider: NuGet
    api_key:
      secure: H9AFeC6uNE88rUiZxmDQNt50bhQ0ilMCua/X9s1++dNB0wMHWrKY8xjfM/M2xFja
    on:
      branch: master
      configuration: Release
#      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    auth_token:
      secure: fLTTmcGOM55kigJC4vErpObFmybCtzQtwb4QN55BTNq3GDGaOCoHDoIPxexzO59d
    release: '${Build_Version}'
    description: 'Version ${Build_Version}'
    artifact: NuGet
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
      configuration: Release
      APPVEYOR_REPO_TAG: true