version: '{build}'
image: Visual Studio 2017

# Setup
install:
  - cmd: ./generateSolution.bat

# Assembly infos & csproj patching
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: $(appveyor_repo_tag_name)
  assembly_file_version: $(appveyor_repo_tag_name)
  assembly_informational_version: $(appveyor_repo_tag_name)

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_repo_tag_name)
  package_version: $(appveyor_repo_tag_name)
  assembly_version: $(appveyor_repo_tag_name)
  file_version: $(appveyor_repo_tag_name)
  informational_version: $(appveyor_repo_tag_name)

# Build configurations
platform:
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Build
before_build:
  - nuget restore

build:
  verbosity: normal

# Artifact
artifacts:  
  - path: .\bin\library\release\**\*.nupkg
    name: NuGet

# Deploy
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/kernelith-ci/api/v2/package
    api_key:
      secure: ANF+joC2B+NahxCFbLPOjNvEAo36F2F4QJu6zLwoIf2I9KwkxKyCSuNxDpLmJmtU
    skip_symbols: true
    on:
      branch: master
      #appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: H9AFeC6uNE88rUiZxmDQNt50bhQ0ilMCua/X9s1++dNB0wMHWrKY8xjfM/M2xFja
    on:
      branch: master
      configuration: Release
      appveyor_repo_tag: true